{% set name = "compas_slicer" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_slicer-{{ version }}.tar.gz
  sha256: a54c659dbffaaede95cb0e664719d30af86884f8dcadc0b439602763df637e1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - compas >=1.16.0,<2.0.0
    - networkx >=2.5,<3.2
    - numpy <=1.23.2
    - progressbar2 >=3.53,<4.4
    - pyclipper >=1.2.0,<1.3.0
    - rdp ==0.8
    - igl
    - python >=3.6

test:
  imports:
    - compas_slicer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/compas-dev/compas_slicer
  summary: Slicing package for FDM 3D Printing with COMPAS
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joburger
    - ioannaMitropoulou
    - gonzalocasas
